# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('bairro', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
