# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_advisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
