# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170928_1627'),
        ('user', '0003_auto_20170928_1802'),
    ]

    operations = [
    ]
