# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('members', models.TextField()),
            ],
        ),
    ]
