# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionList', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.TextField(choices=[('O', 'Objetivas'), ('D', 'Discursivas')], default='Objetivas')),
                ('description', models.TextField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.Checklist')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSchool', models.TextField()),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('county', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('principal', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='schools',
            field=models.ManyToManyField(to='checklist.School'),
        ),
    ]
