# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('SR', 'Sem resposta')], default='SR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('TA', 'Questões técnicas e administrativas'), ('HS', 'Questões Higiênico Sanitárias'), ('O', 'Questões orçamentárias')], default=1, max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('TA', 'Questões técnicas e administrativas'), ('HS', 'Questões Higiênico Sanitárias'), ('O', 'Questões orçamentárias')], default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSchool', models.TextField()),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('county', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
                ('principal', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='checklist.School'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklist.Checklist'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklist.Question'),
        ),
    ]
